#title in header
title: "OxNullPath Blog"

#main info
#owner
owner: "I am OxNullPath"
email: luyanfcp@gmail.com
info: "ğŸŒŸNo mountain too high, no ocean too deep.ğŸŒŸ"
#description
# desc: "I am a System Engineer with 2 years of experience at Alibaba Cloud, specializing in operations and control platform development. I have extensive knowledge in distributed storage systems and management platforms. My technical expertise includes proficiency in C++, C, and Python programming languages, along with working knowledge of JavaScript. I am particularly interested in Rust and actively exploring its applications in system programming."

#menu
menu:
  Works: /workers
  About: /about

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Beijing, China
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/luyanfcp
linkedin: https://www.linkedin.com/in/lu-yan-6855a6280/
twitter: https://x.com/luyanfcp
instagram: https://www.instagram.com/luyanfcp/

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
